WiproDigital/WiproDigital.WebCrawler.UI/Models/ErrorViewModel.cs
using System;

namespace WiproDigital.WebCrawler.UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WiproDigital/WiproDigital.WebCrawler.UI/Models/WebCrawlerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WiproDigital.WebCrawler.UI.Models
{
    public class WebCrawlerViewModel
    {
        [Required]
        public string Url { get; set; }

        public TimeSpan Duration { get; set; }

        public HashSet<HashSet<string>> SiteStructureLinkGroups { get; set; }

        public int? PageIndex { get; set; }
    }
}

WiproDigital/WiproDigital.WebCrawler.UI/Controllers/WebCrawlerController.cs
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using WiproDigital.WebCrawler.Abstractions;
using WiproDigital.WebCrawler.UI.Models;

namespace WiproDigital.WebCrawler.UI.Controllers
{
    public class WebCrawlerController : Controller
    {
        private readonly IWebCrawler _webCrawler;

        private readonly ILogger<WebCrawlerController> _logger;

        public WebCrawlerController(ILogger<WebCrawlerController> logger)
        {
            _webCrawler = WebCrawler.Instance;

            _logger = logger;
        }

        [HttpGet]
        public IActionResult Index(WebCrawlerViewModel webCrawlerViewModel, int? page = 1)
        {
            if (!ModelState.IsValid)
                ModelState.Clear();

            if (TempData.ContainsKey("ViewModel") && TempData["ViewModel"] != null)
            {
                webCrawlerViewModel = JsonConvert.DeserializeObject<WebCrawlerViewModel>(TempData["ViewModel"].ToString());

                TempData.Keep("ViewModel");
            }

            if (webCrawlerViewModel == null)
                webCrawlerViewModel = new WebCrawlerViewModel();

            ViewData["Visible"] = true;

            if (webCrawlerViewModel.SiteStructureLinkGroups == null || webCrawlerViewModel.SiteStructureLinkGroups.Count == 0)
                ViewData["Visible"] = false;

            webCrawlerViewModel.PageIndex = page;

            return View(webCrawlerViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Crawl(WebCrawlerViewModel webCrawlerViewModel)
        {
            _logger.Log(LogLevel.Information, new EventId(), $"Crawl {webCrawlerViewModel.Url}{Environment.NewLine}", null, (s, e) => { return null; });

            ViewData["Visible"] = true;

            if (!string.IsNullOrWhiteSpace(webCrawlerViewModel.Url))
            {
                var stopWatch = new Stopwatch();

                stopWatch.Start();

                var links = await _webCrawler.Crawl(webCrawlerViewModel.Url);

                stopWatch.Stop();

                if (links.Count > 0)
                {
                    webCrawlerViewModel.SiteStructureLinkGroups = _webCrawler.GetSiteStructure(links);
                    webCrawlerViewModel.Duration = stopWatch.Elapsed;

                    _logger.Log(LogLevel.Information, new EventId(), $"Result{Environment.NewLine}", null, (s, e) => { return null; });
                    _logger.Log(LogLevel.Information, new EventId(), $"{webCrawlerViewModel.SiteStructureLinkGroups.Count}{Environment.NewLine}", null, (s, e) => { return null; });
                }
            }
            else
                _logger.Log(LogLevel.Error, new EventId(), "The URL is invalid.", null, (s, e) => { return null; });

            if (webCrawlerViewModel.SiteStructureLinkGroups == null || webCrawlerViewModel.SiteStructureLinkGroups.Count == 0)
            {
                ViewData["Visible"] = false;

                return View("Index", webCrawlerViewModel);
            }

            TempData["ViewModel"] = JsonConvert.SerializeObject(webCrawlerViewModel);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult About()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Sample()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WiproDigital/WiproDigital.WebCrawler.UI/ViewComponents/PaginationViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WiproDigital.WebCrawler.UI.Control;

namespace WiproDigital.WebCrawler.UI.ViewComponents
{
    public class PaginationViewModel
    {
        public PaginationViewModel(Pagination pagination)
        {
            Pagination = pagination;
        }

        public Pagination Pagination { get; }
    }

    [ViewComponent(Name = "Pagination")]
    public class PaginationViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(PaginationViewModel paginationViewModel)
        {
            return View(paginationViewModel);
        }
    }
}

WiproDigital/WiproDigital.WebCrawler.UI/Views/Shared/Components/Pagination/Default.cshtml
@model PaginationViewModel

@{
    var pagination = Model.Pagination;
}
<div class="panel">
    <p>Page @(pagination.TotalPages < pagination.CurrentPage ? 0 : pagination.CurrentPage) of @pagination.TotalPages</p>

    @if (pagination.EndPage > 1)
    {
        <ul id="pager" class="pagination">
            @if (pagination.CurrentPage > 1)
            {
                <li><a href="?page=1#pager">First</a></li>
                <li><a href="?page=@(pagination.CurrentPage - 1)#pager">Previous</a></li>
            }

            @for (var p = pagination.StartPage; p <= pagination.EndPage; p++)
            {
                <li><a href="?page=@p#pager">@p</a></li>
            }

            @if (pagination.CurrentPage < pagination.TotalPages)
            {
                if (pagination.TotalPages - pagination.EndPage > 1)
                {
                    <li><a href="#">&hellip;</a></li>
                    <li><a href="?page=@pagination.TotalPages#pager">@pagination.TotalPages</a></li>
                }

                <li><a href="?page=@(pagination.CurrentPage + 1)#pager">Next</a></li>
                <li><a href="?page=@pagination.TotalPages#pager">Last</a></li>
            }
        </ul>
    }
</div>

WiproDigital/WiproDigital.WebCrawler.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | Wipro Digital Web Crawler</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="WebCrawler" asp-action="Index" class="navbar-brand">Wipro Digital Web Crawler</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="WebCrawler" asp-action="Index">Crawler</a></li>
                    <li><a asp-area="" asp-controller="WebCrawler" asp-action="Sample">Sample</a></li>
                    <li><a asp-area="" asp-controller="WebCrawler" asp-action="About">About</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <h1>@ViewData["Heading"]</h1>
        @RenderBody()
        <footer>
            <p>&copy; 2018 Ryan Anderson</p>
        </footer>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

WiproDigital/WiproDigital.WebCrawler.UI/Views/WebCrawler/About.cshtml
@{
    ViewData["Title"] = "About";
    ViewData["Heading"] = "About";
}

<h2> Wipro Digital Web Crawler Utility</h2>

<br />

<h3>Author</h3>

<p>Ryan E. Anderson</p>

<hr />

<h3>Description</h3>

<p>This utility can be used to efficiently crawl a website to gather links and produce the structure of a site. This solution contains five projects: WiproDigital.Utility, WiproDigital.WebCrawler, WiproDigital.WebCrawler.Abstractions, WiproDigital.WebCrawler.Test, and WiproDigital.WebCrawler.UI. The web crawler works by repeatedly invoking a method to gather all nested links based on an initial set from the first page of a provided URL.</p>

<hr />

<h3>Technologies</h3>

<ul class="list-group">
    <li class="list-group-item">
        ASP.NET Core 2.0
    </li>
    <li class="list-group-item">
        C#
    </li>
    <li class="list-group-item">
        ASP.NET Core MVC
    </li>
    <li class="list-group-item">
        xUnit
    </li>
    <li class="list-group-item">
        Moq
    </li>
    <li class="list-group-item">
        Bootstrap 3.3.7
    </li>
    <li class="list-group-item">
        HTML
    </li>
    <li class="list-group-item">
        CSS
    </li>
    <li class="list-group-item">
        Razor
    </li>
    <li class="list-group-item">
        Bash
    </li>
    <li class="list-group-item">
        Markdown
    </li>
    <li class="list-group-item">
        Git
    </li>
    <li class="list-group-item">
        Json.NET
    </li>
</ul>

<h3>Design Patterns</h3>

<ul class="list-group">
    <li class="list-group-item">
        Utility
    </li>
    <li class="list-group-item">
        Lazy Loading
    </li>
    <li class="list-group-item">
        Singleton
    </li>
    <li class="list-group-item">
        Dependency Injection
    </li>
</ul>

<h3>Architectural Patterns</h3>

<ul class="list-group">
    <li class="list-group-item">
        n-Layer
    </li>
    <li class="list-group-item">
        n-Tier
    </li>
    <li class="list-group-item">
        MVC
    </li>
    <li class="list-group-item">
        MVVM
    </li>
</ul>

<hr />

<h3>Version</h3>

<p>1.2.0</p>

<hr />

<h3>License</h3>

<p>None</p>

<hr />

<h3>Instructions for Evaluating the Web Crawler Utility</h3>

<h4>General Setup</h4>

<p>Change to the WiproDigital directory, and open WiproDigital.sln.</p>

<h4>End-to-End Testing</h4>

<ol>
    <li>
        First, ensure that the WiproDigital.WebCrawler.UI project is set as the StartUp project.
    </li>
    <li>
        Run the program to launch the WebCrawler site.
    </li>
    <li>
        Enter a URL.
    </li>
    <li>
        Press the "Crawl" button.
    </li>
</ol>

<h4>Integration/Unit Testing</h4>

<ol>
    <li>
        Copy the WiproDigital.WebCrawler.UI.deps file from the bin directory of WiproDigital.WebCrawler.UI to that of WiproDigital.WebCrawler.Test.
    </li>
    <li>
        In Visual Studio, click on Test from the menu bar, and select Run All Tests.
    </li>
</ol>

WiproDigital/WiproDigital.WebCrawler.UI/Views/WebCrawler/Index.cshtml
@model WebCrawlerViewModel

@{
    ViewData["Title"] = "Web Crawler";
    ViewData["Heading"] = "Web Crawler";
}

<h3>v1.2.0</h3>

<p>Try the web crawler, a utility developed by Ryan Anderson.</p>

<div class="row">
    <div class="col-lg-6">
        <form asp-controller="WebCrawler" asp-action="Crawl" class="form-inline">
            <div class="form-group">
                <label for="url" class="control-label">URL:</label>
                <input type="text" id="url" name="url" class="form-control" asp-for="Url" placeholder="Enter a valid URL..." />
                <button type="submit" class="btn btn-primary">Crawl</button>
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
        </form>
    </div>
    <div class="col-lg-9">&nbsp;</div>
</div>
<div class="row">
    <div id="result" class="col-lg-12">
        @if (bool.TryParse(ViewData["Visible"].ToString(), out bool checkedVisbility) && checkedVisbility)
        {
            <h4>Result</h4>
            <p>Duration: @Model.Duration.Seconds s</p>
            <p>Groups: @Model.SiteStructureLinkGroups.Count</p>
            <p>Links: @Model.SiteStructureLinkGroups.Sum(x => x.Count)</p>
            <hr />
            <h4>Site Map</h4>
            <ul class="list-group">
                @{
                    var pagination = new Pagination(Model.SiteStructureLinkGroups.Count, Model.PageIndex ?? 1, 5);

                    var linkGroups = Model.SiteStructureLinkGroups.Skip((pagination.CurrentPage - 1) * pagination.PageSize).Take(pagination.PageSize);
                }

                @foreach (var linkGroup in linkGroups)
                {
                    var first = linkGroup.FirstOrDefault();

                    if (string.IsNullOrWhiteSpace(first))
                    {
                        continue;
                    }

                    var tokens = first.Split('/');
                    var token = tokens[tokens.Length > 1 ? 1 : 0];

                    @:<li class="list-group-item"><b>@(string.IsNullOrWhiteSpace(token) ? "/" : token)</b></li>
                    foreach (var link in linkGroup)
                    {
                        @: <li class="list-group-item"><a href=@($"{Model.Url}{link}")>@link</a></li>
                    }
                }
            </ul>
            @await Component.InvokeAsync("Pagination", new { paginationViewModel = new PaginationViewModel(pagination) })
        }
    </div>
</div>

WiproDigital/WiproDigital.WebCrawler.UI/Views/WebCrawler/Sample.cshtml
@{
    ViewData["Title"] = "Sample";
    ViewData["Heading"] = "Sample";
}

<p>Below are links to static HTML pages that contain sample paths for test scenarios.</p>

<ul>
    <li>
        <a href="~/html/StaticSampleAbsolutePath.html">Static Sample Absolute Path</a>
    </li>
    <li>
        <a href="~/html/StaticSampleFragment.html">Static Sample Fragment</a>
    </li>
    <li>
        <a href="~/html/StaticSampleQuery.html">Static Sample Query</a>
    </li>
    <li>
        <a href="~/html/StaticSampleRelativePath.html">Static Sample Relative Path</a>
    </li>
    <li>
        <a href="~/html/StaticSampleSubdomain.html">Static Sample Subdomain</a>
    </li>
</ul>